### PR TITLE
Re-enable cache on Python 3

### PR DESCRIPTION
**Pull request by olebole**
The main bug on Python 3 was spacetelescope/stsci.tools#141. When this is applied, we can re-enable it.

Note that the implementation does not work concurrently. If two processes write to the cache at the same time, the cache file will  get corrupt. In the tests, this is the case when the test script (which itself has the cache open) runs pyraf child instances. The current solution here is to use a different cache for the childs; however this still needs to be resolved.

@jehturner @cdsontag you are invited to give comments here :smile:

### CODE REVIEW

**Comment by jehturner** [comment]
Just to clarify, is this _"if two processes write to the cache at the same time, the cache file will get corrupt"_ a new thing? I think there has always been contention between pyraf processes sharing the same uparm files & cache in Python 2, hasn't there? But are you referring to the file structure getting corrupted in a way that didn't happen in Python 2, rather than just a race to determine the contents?

**Comment by olebole** [comment]
The corruption depends on the implementation of the `shelve` module that is used as the backend to store the compiled CL files. And [the documentation of `shelve` says clearly](https://docs.python.org/3/library/shelve.html#restrictions): 

> The shelve module does not support concurrent read/write access to shelved objects. (Multiple simultaneous read accesses are safe.) When a program has a shelf open for writing, no other program should have it open for reading or writing. 

And this is easily visible with the current source: when one (with enabled cache, but without c02408a) try to run `python3 -m pytest` *three* times, the third invocation warns about a corrupt database. If one uses a different database for the "pyraf" child instances in `test_invocation.py`, everything works well.

I would guess the same happens with the old, Python 2 version as well, since it is the same code. But this is not sure, as it depends on the internals of `shelve`, and of the specific timing of the concurrent access.

The robust solution here would be to replace `shelve` with an implementation that allows concurrent access. On a first thought, there are two ways to robustly re-implement `shelve`:
 1.  as a list of files (file name as key) in a directory,
 2.  using a simple SQLite database, like here: [devnull255/sqlite-shelve](https://github.com/devnull255/sqlite-shelve).

I probably will go the second way, since the implementation is rather simple, and it is more extensible. But this will (again) be another PR.

**Comment by sosey** [comment]
I'm just here to give you 👏 👏 👏  for all this work ole!

**Comment by jehturner** [comment]
Yes, thanks @olebole. I was hoping to test this but have been troubleshooting other things and it's best to let you finish what you're in the middle of anyway.

**Comment by olebole** [comment]
Whoever wants to test this before merging, please do now. I think this is ready to merge and will merge tomorrow if there is no further comment here.

**Pull request merged**
