### PR TITLE
Remove Python 2 support and improve Python 3 style

### PR DESCRIPTION
**Pull request by olebole**
This PR removes all Python 2 specific code and strengthens the code for improved possibilities with Python 3.
Aside from this, the deprecation warnings for `numpy.fromstring()` and the `imp` module are fixed. 

There is a new branch [python2](https://github.com/iraf-community/pyraf/tree/python2) starting just before this PR.

### CODE REVIEW

**Comment by jehturner** [comment]
Hi Ole,

:open_mouth: Remove Python 2 support? Have you managed to implement the "clcache" translation (or whatever you call it) that pyraf was missing for Python 3? (That would be interesting.) Otherwise it can be extremely slow under 3... Just saying! That's why we still use 2 for IRAF. Hope you are well.

James.

**Comment by olebole** [comment]
Yea, STScI removed Python 2 support from stsci.tools as well (spacetelescope/stsci.tools#121), and that is a dependency. There is a "[python2](https://github.com/iraf-community/pyraf/tree/python2)" branch for the case we still need an update there.
clcache works nicely with Python 3; the major problem was in STScI tools: spacetelescope/stsci.tools#141. After applying this, it runs like a charm. 
Re-enabling is not in this PR; I will open another one tomorrow or so; I still feel unhappy with the idea to have the "system cache" in the PyRAF package dir; IMO it should go to whatever the system defines as a cache location (in the `/var/cache/` tree in Linux, to find out on the Mac). But this shall be discussed there (I'll invite your :smiley: )

**Comment by jehturner** [comment]
Huh! That sounds great :slightly_smiling_face:. I believe I got the impression from @cdsontag in 2018 that the cacheing would be non-trivial to get working and we weren't all that familiar with the code and had been having a problem with constantly getting dragged back into IRAF rabbit holes rather than making progress on our Python package. Looking back at some old emails though (also from 2014), he didn't actually say that it would be hard... I suppose we just had to draw a line somewhere, the same as STScI -- but I'd already fixed a handful of problems on Python 3 and it looks like I stopped slightly too soon :grimacing:.

The whole Python 2 stack depends on old versions (including Python 2 itself), so PyRAF depending on an old version of `stsci.tools` is just one more thing -- but if your patch lets us get rid of Python 2 (or at least removes the uncertainty about what's needed) that's another matter entirely :clap::clap:. I'll have to do a bit of testing, but this seems as if using Python 3 might be viable now (more so than switching from 32-bit IRAF, in spite of the M1 thing, which I see you've also done some work on).

So does STScI consider this the main pyraf repo now (@pllim? @sosey?). That may be a bit moot if it's the only one being actively maintained after they dropped IRAF support, but it seems like they're helping you out a little bit and I imagine they'd rather not receive PRs...

**Comment by pllim** [comment]
> STScI consider this the main pyraf repo now

Yes, I think so. `spacetelescope/pyraf` is archived. 😬 

> helping you out a little bit

Of course, happy to help where we can, though we do not have funding for big work.

**Comment by cdsontag** [comment]
> I believe I got the impression from @cdsontag in 2018 that the cacheing would be non-trivial to get working and 

@jehturner  - I do recall this but I think it was just a good "stopping point" in the port since it was important but not critical (runs without it) and was going to be extra work so it could be kicked down the road a bit.

Glad PyRAF is still moving forward.

**Comment by jehturner** [comment]
Following #82 (which resolved #61), I have been able to run our Gemini IRAF regression tests on the main branch (`8ea61699`) with Python 3. About a quarter of our 932 tests fail, with what look like about ~10 failure modes, which is not terrible :slightly_smiling_face:. I'll have to troubleshoot these further at a later date, since I'm way behind with projects scheduled for this year (ending in Sept), but I would say the prospects of us being able to switch to the "iraf-community" pyraf at some point seem pretty good. In the meantime, I'll enter an issue for the first problem I encountered, which is one of the main ones and is not difficult to reproduce (I'll also try solving it later, if no-one else does). Thanks, Ole. I would say you can be quite confident about the behaviour with respect to Python 2 if we can get our tests working...

**Comment by olebole** [comment]
@jehturner I'd love to get the bug reports from you! Gemini is probably a very useful test.

**Comment by olebole** [comment]
@jehturner, I would like to proceed to tag a new PyRAF version (2.2). It would be nice to have the Gemini problems fixed there. Can you open issues for them? or shall I release and we create a bugfix release afterwards?

**Comment by jehturner** [comment]
Hi @olebole, I'd estimate that I should be able to work on this at some point the week after next if that helps? Thanks for asking.

**Comment by olebole** [comment]
I think that is fine. I would create a 2.2.0rc in the next days, also to learn how to upload to PyPI...

**Pull request merged**
