### PR TITLE
Resolve "Error in parameter" with additional pset dot syntax (#113)

### LINKED ISSUE #113: "Error in parameter" (sometimes) with additional pset dot syntax
I'm seeing quite a lot of Gemini IRAF tests failing with a message such as `KeyError: "Error in parameter 'centerpars.cthreshold' for task phot\n'Key centerpars.cthreshold not found'"`, using a recent checkout of iraf-community PyRAF for Python 3. All but one are cases where the failing IRAF task gets passed parameters from an "additional" pset (can't recall whether that's the proper IRAF terminology) in the form `centerpars.cthreshold=0.`.

For example, I see the error quoted above when doing the following with pyraf 2.2.1.dev3 and stsci.tools 4.0.1 on Python 3.7.9:
```
digiphot
apphot

phot dev$pix coords="" output="default" interactive- centerpars.calgorithm="none" centerpars.cthreshold=0.
```
This only happens some of the time, depending on the exact parameters used, due to the nature of the bug. With earlier PyRAF releases, the task instead continues to a prompt like the following in this particular case (which seems like dubious behaviour in itself, but that's a different problem!):
```
Centering algorithm (none) (CR or value): 
```
After a bit of troubleshooting, this seems to be a regression introduced by no longer running `2to3` on the source code (making it hard to spot, since there's no change to the offending line in the revision history!). Because `kw.keys()` no longer gets converted to a `list` by `2to3`, the following block of code is now modifying a `dict` in place while iterating over it (rather than over an existing copy of the keys), leading to unpredictable behaviour:

https://github.com/iraf-community/pyraf/blob/1a63a6525b2b95bdc0597b2b8e84c99f52eb829c/pyraf/irafpar.py#L912-L918

I think the solution is just to put L912 back to this (or use `copy` or something):
```python
        for key in list(kw.keys()):
```
Thanks!

James.

### PR DESCRIPTION
**Pull request by jehturner**
Here's the prospective bug fix for #113. What else is needed? I don't see a change log and (as mentioned) I only have a working test in CL...

Fixes #113.

### CODE REVIEW

**Comment by jehturner** [comment]
I could try a bit harder to reproduce how we run CL tests if necessary, but I'm not sure it's worth it here (also I'd need to find a failure mode that doesn't prompt `interactively) and it seems more important to document our other test failures, so I'll come back to this once you've commented on it, @olebole.

**Comment by olebole** [comment]
You are right; I thought that I checked all occurences of the `for x in y.keys(): …` during the 2to3 conversion; however this one slipped through. A re-check found another one; I'll append it to your patch. I also found a place where `list` was used as variable; for safety I replaced that with `list_` to not accidently hide the original function.

I don't think there is too much urgency to write a test for it: IMO the fix is obvious by manual review, and I can't think of a test that would point us to other, similar problems.

**Comment by olebole** [comment]
For the changelog: since the development will probably not turn heavy in the future, I didn't make efforts for a changelog (also because there was no such thing in the past here). Instead, I thought to just manually copy the headlines of the merged Pull Requests into the release notes, as I did for [version 2.2.0](https://github.com/iraf-community/pyraf/releases).
But I am open for better ideas :-)

**Comment by jehturner** [comment]
Seems good to me. It is useful to have some kind of summary of what's changed since you took over PyRAF, but best keep the effort minimal since it's not like there are lots of contributors writing tests & documentation etc :slightly_smiling_face:. What you did for 2.2.0 makes it easy to drill down into the details if someone wants to :+1:.

**Comment by jehturner** [comment]
Is there anything else I can do here (apart from re-testing it after fixing a couple of other things)?

**Comment by olebole** [comment]
I think that is OK. I would leave this PR open until tomorrow (UTC) just to let it mature :grin: and then merge it.

**Pull request merged**
