### PR TITLE
Fix pickle protocol

### LINKED ISSUE #142: `Unsupported pickle protocol` for clcache
Hi Ole. Related to #132, I notice that if I test `pyraf` under Python 3.8-3.9 and then go back to running it (in the same directory) from a Python 3.7 environment, I am greeted with the following error when trying to load certain packages, or even when starting `pyraf` itself (depending on which Python was used first for loading which packages):
```
ValueError: unsupported pickle protocol: 5
```
According to [the documentation](https://docs.python.org/3/library/pickle.html#pickle.DEFAULT_PROTOCOL), although protocol version 5 was introduced in 3.8, the latter uses version 4 by default, which I think should be compatible with any Python that people might use with `2.2.1`. But it looks that your `sqliteshelve.py` module explicitly specifies `HIGHEST_PROTOCOL`. Perhaps if there's a compelling reason to prefer v5 then either it would be better to trap this error, ignore the unsupported cache entry and make a duplicate one (so it "just works"?) or at least to add a less cryptic error saying "delete your `pyraf/` cache", so people know what to do about it? Thanks.

### PR DESCRIPTION
**Pull request by olebole**
Protocol version 4 is supported since Python 3.4 and the default starting with Python 3.8.

Fixing the protocol version allows to downgrade the Python version. To make it more robust, also trigger a re-build of the cache entry if the cache was written by an unsupported protocol version.

Fixes #142.

### CODE REVIEW

**Comment by jehturner** [comment]
Thanks, Ole!

This fixes my problem with starting PyRAF under 3.7 after initially creating the cache under 3.9 (both with this branch). However, if I start PyRAF under 3.7 with an existing cache entry for "gemini" that was created using 2.2.1 under Python 3.8, I get this when trying to load the package:
```
PyRAF 2.2.1.dev53+g50abdfe
Python/CL command line wrapper
  .help describes executive commands
--> gemini
Traceback (innermost last):
  File "<CL script CL1>", line 1, in <module>
KeyError: 'fd14f25516d1b332bba797340d93d9494c'
```
Not sure how much we care about that (I have a meeting now, so don't have much time to think about it) but it doesn't seem as intended?

**Comment by jehturner** [comment]
The above error (from the new `try ... except`, at L113) only occurs when using PyRAF 2.2.1 on Python 3.8/3.9, followed by this branch on 3.7. The comment suggests that the `KeyError` will cause the cache entry to be rebuilt, but apparently that is not happening?

**Comment by olebole** [comment]
The idea was that when the id is not there, the old version is overwritten by one with a new pickle version. This however appears not to work.
Then, probably the best solution is to add the pickle protocol to the version string. Can you try this out again?

**Comment by jehturner** [comment]
That version seems fine, thanks (on Linux). I suppose it will mean more old duplicate entries sitting around, but I never really see more than a few MB and people can delete them if they want to.

**Comment by olebole** [comment]
That is true; however this will happen also when we introduce another incompatible change (which changes the version of the cache). And I think that we will very rarely change the pickle protocol in future.

**Comment by temuller** [comment]
Hi! I don't think this has been added to the latest version, right? pip installs pyraf v2.2.1, but this fix is not included.

**Comment by olebole** [comment]
No, it is not included in 2.2.1. I didn't make a new release because downgrading Python seemed a rare case, and one can work around the problem by removing the cache after downgrading.

**Pull request merged**
