### PR TITLE
Resolve CL syntax error when assigning value to array element on Py 3 (#115)

### PR DESCRIPTION
**Pull request by jehturner**
Fixes: #115

### CODE REVIEW

**Comment by olebole** [comment]
Thank you for the PR! This looks OK for me; I would merge it tomorrow or so.

**Comment by jehturner** [comment]
Should the test have a `tmpdir` parameter, like the others and your example? It seems to work without one, but this `pytest` stuff a bit opaque. Also, I think this test probably doesn't require IRAF, right?

**Comment by olebole** [comment]
`tmpdir` is a [pytest fixture](https://docs.pytest.org/en/6.2.x/tmpdir.html) which can be used as a temporary directory during the run. Its use in these PyRAF tests goes back to 2018, but I think in most cases (and all in `test_cli.py`) it can be just removed. If you like you can do it; otherwise I would create a new PR before a new release.

**Comment by jehturner** [comment]
Yes, we use pytest fixtures (set up by colleagues) for DRAGONS but I don't find them very _"explicit is better than implicit"_...

I'm under a bit of time pressure to work on something else and I think it would be best for me to concentrate on reporting more test failure modes in the first instance :wink:. I'm just looking at another one (which might be better fixed on our end)...

**Comment by olebole** [comment]
Sure, I will merge this, and make another PR with removing *tmpfile* where it is not needed.

**Pull request merged**
