### PR TITLE
Re-add the tutorial (but as ReStructuredText)

### PR DESCRIPTION
**Pull request by olebole**
This PR adds back the (mainly unchanged) PyRAF tutorial as ReStructured Text. This could be a base for a more comprehensice (API) documentation.

### CODE REVIEW

**Comment by pllim** [comment]
Might as well hook up RTD?

**Comment by olebole** [comment]
I forgot how to do this. If it is simple, please add it :-)

**Comment by pllim** [comment]
I am not sure if I want to be admin here... Instructions at https://docs.readthedocs.io/en/stable/intro/import-guide.html

**Comment by olebole** [comment]
Hmm, the build completes now, but I don't get  a web page. :-(

**Comment by pllim** [comment]
To enable for PR, you need to check the "enable PR build" in RTD admin section. Also need to modify your GitHub-RTD webhook here for RTD. See https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by pllim** [comment]
Once that is done, you probably need to close/re-open this PR for the new settings to kick off.

**Comment by olebole** [comment]
Ahh -- it took some time. At some point, only the direct `…/index.html` worked, but not just the main repo. Now it is there:

https://pyraf.readthedocs.io/en/docs/

**Comment by pllim** [comment]
Very nice!

**Comment by olebole** [comment]
@pllim Thank you for your help!

I now updated the tutorial to somehow reflect the current status, and also added an 'Installation' section (which also made me add my own name to the authors). @rlwastro @perrygreenfield just to be sure: the [tutorial](https://pyraf--100.org.readthedocs.build/en/100/) is licensed in the same manner as PyRAF itself, i.e. I am free to change it as long as you are kept as authors, right?

**Comment by rlwastro** [comment]
I think it is a fair assumption that the same license applies to the tutorial as to the code.  Certainly I don't claim any additional license to it.

I think it's great that you're working to save this code! 👍

**Pull request merged**
